### ISSUE TITLE
found "committed" a misspelling of "comitted"

### ISSUE THREAD

**Issue by riyazdf** [client9/misspell#35] opened 2016-03-08 23:25 UTC
After upgrading to the latest version earlier today, I think there might be a mistake with the misspelling error: `committed` should be the correct spelling

```
+ misspell
./tuf/tuf.go:317:64:found "committed" a misspelling of "comitted"
```
(code comment here: https://github.com/docker/notary/blob/master/tuf/tuf.go#L317)

**Comment by client9** [comment] 2016-03-09 01:13
hmm, I will look!
thanks for report

**Comment by client9** [comment] 2016-03-09 01:29
should be fixed now.  The problem was caused by conflicting rules for "omit" and "commit"

**Comment by riyazdf** [comment] 2016-03-09 01:30
just verified, thanks for resolving this so quickly! :+1:

**Closed by client9** 2016-03-09 01:29 UTC
